[package]
name = "freemap-outdoor-map"
version = "1.0.0"
edition = "2024"
publish = false

[dependencies]
image = { version = "0.25", default-features = false, features = [
  "jpeg",
  "png",
] }
librsvg = { version = "2.61" }
bitflags = "2.10.0"
cairo-rs = { version = "0.21", features = ["png", "svg", "pdf"] }
cavalier_contours = { version = "0.7.0" }
colorsys = "0.7"
geo-postgis = "0.2.2"
pangocairo = "0.21"
postgis = "0.9"
proj = { version = "0.29", features = ["geo-types"] }
gio = "0.21.5"
xmltree = "0.12.0"
gdal = { version = "0.19", features = ["bindgen"] }
geo = { version = "0.30.0", features = ["use-proj"] }
geojson = "0.24"
postgres = "0.19"
r2d2 = "0.8"
r2d2_postgres = "0.18"
regex = "1.11"
serde_json = "1.0.149"
tracy-client = "0.18.4"
thiserror = "2.0.17"
axum = "0.8.8"
clap = { version = "4.5.18", features = ["derive", "env"] }
dotenvy = "0.15.7"
tokio = { version = "1.40.0", features = ["fs", "macros", "rt-multi-thread"] }
tower = { version = "0.5.1", features = ["limit", "timeout"] }
rand = "0.9.2"
serde = { version = "1.0.217", features = ["derive"] }
notify = "8.2.0"
fs2 = "0.4.3"
tokio-util = { version = "0.7.12", features = ["io"] }
